# cloudbuild.yaml (גרסת Monorepo)
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - '${_FUNCTION_NAME}'  # <-- משתנה: שם הפונקציה
    - '--source=./functions/${_FUNCTION_NAME}' # <-- משתנה: נתיב לקוד
    - '--gen2'
    - '--region=${_REGION}'  # <-- משתנה: אזור
    - '--runtime=python312'
    - '--entry-point=${_ENTRY_POINT}' # <-- משתנה: שם הפונקציה בקוד
    - '--trigger-http'
    - '--allow-unauthenticated'
    - '--set-env-vars=API_KEY=${_API_KEY},SEARCH_ENGINE_ID=${_SEARCH_ENGINE_ID}'

# הגדרת משתני סביבה מאובטחים
substitutions:
  _API_KEY: 'projects/YOUR_PROJECT_ID/secrets/API_KEY/versions/latest'
  _SEARCH_ENGINE_ID: 'projects/YOUR_PROJECT_ID/secrets/SEARCH_ENGINE_ID/versions/latest'

options:
  logging: CLOUD_LOGGING_ONLY
