steps:
# צעד דיבאג כדי לראות את מבנה התיקיות
- name: 'ubuntu'
  args: ['ls', '-R']
  id: 'List Files'

# צעד הפריסה הראשי
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'gcloud'
  - 'functions'
  - 'deploy'
  - '${_FUNCTION_NAME}'
  - '--source=./functions/${_FUNCTION_NAME}'
  - '--entry-point=${_ENTRY_POINT}'
  - '--runtime=python311'
  - '--region=${_REGION}'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--set-secrets=API_KEY=${_API_KEY},SEARCH_ENGINE_ID=${_SEARCH_ENGINE_ID}'
  # הוספת השורה הזו היא זו שגרמה לבעיית הלוגים.
  # ודא שהיא מכילה את חשבון השירות הנכון של Cloud Build.
  serviceAccount: 'projects/idea-garden-266a2/serviceAccounts/cloud-build-custom-sa@idea-garden-266a2.iam.gserviceaccount.com'

substitutions:
  _API_KEY: 'projects/idea-garden-266a2/secrets/API_KEY/versions/latest'
  _SEARCH_ENGINE_ID: 'projects/idea-garden-266a2/secrets/SEARCH_ENGINE_ID/versions/latest'

# הבלוק הזה אומר ל-Cloud Build להמשיך להשתמש ב-Cloud Logging כרגיל.
options:
  logging: CLOUD_LOGGING_ONLY




options:
  logging: CLOUD_LOGGING_ONLY
